apiVersion: v2
name: authentik
description: Authentik bridge — SAML SP to Duo, OIDC IdP to Grafana / Jenkins / ArgoCD
version: 1.0.0
appVersion: "2026.2.4"
dependencies:
  - name: authentik
    version: 2026.2.3
    repository: https://charts.goauthentik.io
